<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.9 setup script
 * Date: Sat, 13 Jun 2015 05:57:33 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: 104.131.80.193 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '104.131.80.193';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '557baa1c3f32d3.63946604';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>